// Code generated by marten vdev; DO NOT EDIT.

package search

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/scale-flow/dj/internal/dj"
	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
	"github.com/Scale-Flow/marten/pkg/transport"
)

// NewSearchCmd creates the search command.
func NewSearchCmd() *cobra.Command {
	return newSearchCmd()
}

func newSearchCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "search",
		Short: "Search Spotify for tracks, albums, or artists",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runSearch(cmd, args)
		},
	}

	cmd.Flags().String("q", "", "Search query (supports field filters: artist:, album:, track:, year:, genre:)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().String("type", "", "Comma-separated types: track,album,artist")
	_ = cmd.MarkFlagRequired("type")
	cmd.Flags().String("market", "", "ISO 3166-1 alpha-2 country code")
	cmd.Flags().Int("limit", 0, "Results per page (max 50)")
	cmd.Flags().Int("offset", 0, "Result offset for pagination")

	return cmd
}

func runSearch(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	token, err := cmdutil.ResolveAuth(cmd.Context(), cmdutil.AuthConfig{
		Strategy:          "oauth2",
		ConfigDir:         "dj",
		ProfileName:       rctx.ProfileName,
		AllowFileFallback: true,
		OAuthStorePath:    storePath,
		OAuthMetadataPath: oauthMetadataPath(storePath),
		RefreshConfig: &oauth.RefreshConfig{
			TokenURL: "https://accounts.spotify.com/api/token",
		},
	})
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	t := transport.NewClient(rctx.BaseURL, token, "Authorization", "Bearer ")
	client := dj.NewClient(t, rctx.Extra)
	flagQ, _ := cmd.Flags().GetString("q")
	flagType, _ := cmd.Flags().GetString("type")
	flagMarket, _ := cmd.Flags().GetString("market")
	flagLimit, _ := cmd.Flags().GetInt("limit")
	flagOffset, _ := cmd.Flags().GetInt("offset")

	if cmdutil.DryRun(cmd) {
		pathParams := map[string]string{
		}
		fullPath := client.BuildPath("/v1/search", pathParams)
		return cmdutil.WriteDryRun(cmd, "GET", rctx.BaseURL+fullPath, nil)
	}

	pathParams := map[string]string{
	}
	fullPath := client.BuildPath("/v1/search", pathParams)
	queryParams := map[string]string{
		"q": flagQ,
		"type": flagType,
		"market": flagMarket,
	}
	if flagLimit != 0 {
		queryParams["limit"] = fmt.Sprintf("%d", flagLimit)
	}
	if flagOffset != 0 {
		queryParams["offset"] = fmt.Sprintf("%d", flagOffset)
	}
	fullPath += dj.BuildQueryString(queryParams)

	var result dj.SearchResult
	if err := client.DoGet(cmd.Context(), fullPath, &result); err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeServer, err.Error())
	}
	return cmdutil.WriteSuccess(cmd, result)
}
