// Code generated by marten vdev; DO NOT EDIT.

package search

import (
	"fmt"
	"github.com/scale-flow/dj/internal/cli/cliutil"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/scale-flow/dj/internal/dj"
)

// NewSearchCmd creates the search command.
func NewSearchCmd() *cobra.Command {
	return newSearchCmd()
}

func newSearchCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "search",
		Short: "Search Spotify for tracks, albums, or artists",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runSearch(cmd, args)
		},
	}

	cmd.Flags().String("q", "", "Search query (supports field filters: artist:, album:, track:, year:, genre:)")
	_ = cmd.MarkFlagRequired("q")
	cmd.Flags().String("type", "", "Comma-separated types: track,album,artist")
	_ = cmd.MarkFlagRequired("type")
	cmd.Flags().String("market", "", "ISO 3166-1 alpha-2 country code")
	cmd.Flags().Int("limit", 0, "Results per page (max 50)")
	cmd.Flags().Int("offset", 0, "Result offset for pagination")

	return cmd
}

func runSearch(cmd *cobra.Command, args []string) error {
	rctx, err := cliutil.ResolveSpotifyContext(cmd)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	client := dj.NewClient(nil, rctx.Extra)
	flagQ, _ := cmd.Flags().GetString("q")
	flagType, _ := cmd.Flags().GetString("type")
	flagMarket, _ := cmd.Flags().GetString("market")
	flagLimit, _ := cmd.Flags().GetInt("limit")
	flagOffset, _ := cmd.Flags().GetInt("offset")

	pathParams := map[string]string{}
	fullPath := client.BuildPath("/v1/search", pathParams)
	queryParams := map[string]string{
		"q":      flagQ,
		"type":   flagType,
		"market": flagMarket,
	}
	if flagLimit != 0 {
		queryParams["limit"] = fmt.Sprintf("%d", flagLimit)
	}
	if flagOffset != 0 {
		queryParams["offset"] = fmt.Sprintf("%d", flagOffset)
	}
	fullPath += dj.BuildQueryString(queryParams)

	if cmdutil.DryRun(cmd) {
		return cmdutil.WriteDryRun(cmd, "GET", rctx.BaseURL+fullPath, nil)
	}

	client, err = cliutil.NewSpotifyClient(cmd, rctx)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	var result dj.SearchResult
	if err := client.DoGet(cmd.Context(), fullPath, &result); err != nil {
		return cliutil.WriteAPIError(cmd, err)
	}
	return cmdutil.WriteSuccess(cmd, result)
}
