// Code generated by marten vdev; DO NOT EDIT.

package cliutil

import (
	"bufio"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
)

// ConfirmAction prompts the user for confirmation on stderr.
// Returns true if the user confirms or --yes is set.
func ConfirmAction(cmd *cobra.Command, action string) bool {
	if cmdutil.Confirm(cmd) {
		return true
	}
	fmt.Fprintf(cmd.ErrOrStderr(), "About to %s. Continue? [y/N] ", action)
	reader := bufio.NewReader(cmd.InOrStdin())
	line, _ := reader.ReadString('\n')
	return strings.TrimSpace(strings.ToLower(line)) == "y"
}
