// Code generated by marten vdev; DO NOT EDIT.

package tracks

import (
	"fmt"
	"github.com/scale-flow/dj/internal/cli/cliutil"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/scale-flow/dj/internal/dj"
)

func newGetCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get a track by Spotify ID",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runGet(cmd, args)
		},
	}

	cmd.Flags().String("market", "", "ISO 3166-1 alpha-2 country code")
	cmd.Flags().String("id", "", "Spotify track ID")
	_ = cmd.MarkFlagRequired("id")

	return cmd
}

func runGet(cmd *cobra.Command, args []string) error {
	rctx, err := cliutil.ResolveSpotifyContext(cmd)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	client := dj.NewClient(nil, rctx.Extra)
	flagMarket, _ := cmd.Flags().GetString("market")
	flagID, _ := cmd.Flags().GetString("id")

	pathParams := map[string]string{
		"id": fmt.Sprintf("%v", flagID),
	}
	fullPath := client.BuildPath("/v1/tracks/{id}", pathParams)
	queryParams := map[string]string{
		"market": flagMarket,
	}
	fullPath += dj.BuildQueryString(queryParams)

	if cmdutil.DryRun(cmd) {
		return cmdutil.WriteDryRun(cmd, "GET", rctx.BaseURL+fullPath, nil)
	}

	client, err = cliutil.NewSpotifyClient(cmd, rctx)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	var result dj.Track
	if err := client.DoGet(cmd.Context(), fullPath, &result); err != nil {
		return cliutil.WriteAPIError(cmd, err)
	}
	return cmdutil.WriteSuccess(cmd, result)
}
