// Code generated by marten vdev; DO NOT EDIT.

package tracks

import "github.com/spf13/cobra"

// NewTracksCmd creates the tracks parent command.
func NewTracksCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tracks",
		Short: "Look up track information",
	}

	cmd.AddCommand(newGetCmd())

	return cmd
}
