// Code generated by marten vdev; DO NOT EDIT.

package player

import (
	"github.com/scale-flow/dj/internal/cli/cliutil"
	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/scale-flow/dj/internal/dj"
)

func newDevicesCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "devices",
		Short: "List available Spotify Connect devices",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDevices(cmd, args)
		},
	}

	return cmd
}

func runDevices(cmd *cobra.Command, args []string) error {
	rctx, err := cliutil.ResolveSpotifyContext(cmd)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	client := dj.NewClient(nil, rctx.Extra)

	pathParams := map[string]string{}
	fullPath := client.BuildPath("/v1/me/player/devices", pathParams)

	if cmdutil.DryRun(cmd) {
		return cmdutil.WriteDryRun(cmd, "GET", rctx.BaseURL+fullPath, nil)
	}

	client, err = cliutil.NewSpotifyClient(cmd, rctx)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	var result struct {
		Devices []dj.PlaybackDevice `json:"devices"`
	}
	if err := client.DoGet(cmd.Context(), fullPath, &result); err != nil {
		return cliutil.WriteAPIError(cmd, err)
	}
	return cmdutil.WriteSuccess(cmd, result)
}
