// Code generated by marten vdev; DO NOT EDIT.

package player

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/scale-flow/dj/internal/dj"
	"github.com/scale-flow/dj/internal/cli/cliutil"
	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
	"github.com/Scale-Flow/marten/pkg/transport"
)

func newNextCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "next",
		Short: "Skip to next track (Premium required)",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runNext(cmd, args)
		},
	}

	cmd.Flags().String("device-id", "", "Target device ID (defaults to active device)")

	return cmd
}

func runNext(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	token, err := cmdutil.ResolveAuth(cmd.Context(), cmdutil.AuthConfig{
		Strategy:       "oauth2",
		ProfileName:    rctx.ProfileName,
		OAuthStorePath: storePath,
		RefreshConfig: &oauth.RefreshConfig{
			TokenURL:     "https://accounts.spotify.com/api/token",
			ClientID:     os.Getenv("DJ_CLIENT_ID"),
		},
	})
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	t := transport.NewClient(rctx.BaseURL, token, "Authorization", "Bearer ")
	client := dj.NewClient(t, rctx.Extra)
	flagDeviceID, _ := cmd.Flags().GetString("device-id")

	if cmdutil.DryRun(cmd) {
		body := map[string]any{
		}
		pathParams := map[string]string{
		}
		fullPath := client.BuildPath("/v1/me/player/next", pathParams)
		return cmdutil.WriteDryRun(cmd, "POST", rctx.BaseURL+fullPath, body)
	}

	if !cliutil.ConfirmAction(cmd, "POST /me/player/next") {
		return nil
	}

	body := map[string]any{
	}
	pathParams := map[string]string{
	}
	fullPath := client.BuildPath("/v1/me/player/next", pathParams)
	queryParams := map[string]string{
		"device_id": fmt.Sprintf("%v", flagDeviceID),
	}
	fullPath += dj.BuildQueryString(queryParams)

	if err := client.DoPost(cmd.Context(), fullPath, body, nil); err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeServer, err.Error())
	}
	return cmdutil.WriteSuccess(cmd, nil)
}
