// Code generated by marten vdev; DO NOT EDIT.

package player

import (
	"github.com/scale-flow/dj/internal/cli/cliutil"
	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/scale-flow/dj/internal/dj"
)

func newNowPlayingCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "now-playing",
		Short: "Show the currently playing track",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runNowPlaying(cmd, args)
		},
	}

	cmd.Flags().String("market", "", "ISO 3166-1 alpha-2 country code")

	return cmd
}

func runNowPlaying(cmd *cobra.Command, args []string) error {
	rctx, err := cliutil.ResolveSpotifyContext(cmd)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	client := dj.NewClient(nil, rctx.Extra)
	flagMarket, _ := cmd.Flags().GetString("market")

	pathParams := map[string]string{}
	fullPath := client.BuildPath("/v1/me/player/currently-playing", pathParams)
	queryParams := map[string]string{
		"market": flagMarket,
	}
	fullPath += dj.BuildQueryString(queryParams)

	if cmdutil.DryRun(cmd) {
		return cmdutil.WriteDryRun(cmd, "GET", rctx.BaseURL+fullPath, nil)
	}

	client, err = cliutil.NewSpotifyClient(cmd, rctx)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	var result *dj.NowPlaying
	if err := client.DoGet(cmd.Context(), fullPath, &result); err != nil {
		return cliutil.WriteAPIError(cmd, err)
	}
	return cmdutil.WriteSuccess(cmd, result)
}
