// Code generated by marten vdev; DO NOT EDIT.

package player

import (
	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
	"github.com/Scale-Flow/marten/pkg/transport"
	"github.com/scale-flow/dj/internal/cli/cliutil"
	"github.com/scale-flow/dj/internal/dj"
)

func newPauseCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "pause",
		Short: "Pause playback (Premium required)",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPause(cmd, args)
		},
	}

	cmd.Flags().String("device-id", "", "Target device ID (defaults to active device)")

	return cmd
}

func runPause(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	token, err := cmdutil.ResolveAuth(cmd.Context(), cmdutil.AuthConfig{
		Strategy:          "oauth2",
		ConfigDir:         "dj",
		ProfileName:       rctx.ProfileName,
		AllowFileFallback: true,
		OAuthStorePath:    storePath,
		OAuthMetadataPath: oauthMetadataPath(storePath),
		RefreshConfig: &oauth.RefreshConfig{
			TokenURL: "https://accounts.spotify.com/api/token",
		},
	})
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	t := transport.NewClient(rctx.BaseURL, token, "Authorization", "Bearer ")
	client := dj.NewClient(t, rctx.Extra)
	flagDeviceID, _ := cmd.Flags().GetString("device-id")

	if cmdutil.DryRun(cmd) {
		body := map[string]any{}
		pathParams := map[string]string{}
		fullPath := client.BuildPath("/v1/me/player/pause", pathParams)
		return cmdutil.WriteDryRun(cmd, "PUT", rctx.BaseURL+fullPath, body)
	}

	if !cliutil.ConfirmAction(cmd, "PUT /me/player/pause") {
		return nil
	}

	body := map[string]any{}
	pathParams := map[string]string{}
	fullPath := client.BuildPath("/v1/me/player/pause", pathParams)
	queryParams := map[string]string{
		"device_id": flagDeviceID,
	}
	fullPath += dj.BuildQueryString(queryParams)

	if err := client.DoMethod(cmd.Context(), "PUT", fullPath, body, nil); err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeServer, err.Error())
	}
	return cmdutil.WriteSuccess(cmd, nil)
}
