// Code generated by marten vdev; DO NOT EDIT.

package player_test

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/scale-flow/dj/internal/dj"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/testutil"
	"github.com/Scale-Flow/marten/pkg/transport"
)

func TestCmdPause_Success(t *testing.T) {
	srv := testutil.MockServer(t, 200, `{"ok": true}`)
	defer srv.Close()

	tc := transport.NewClientWithDoer(srv.URL, "test-token", "Authorization", "Bearer ", srv.Client())
	client := dj.NewClient(tc, nil)
	var result dj.
	err := client.DoPost(context.Background(), "/test", map[string]any{}, &result)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
}

func TestCmdPause_ServerError(t *testing.T) {
	srv := testutil.MockServer(t, 500, `{"error": "internal server error"}`)
	defer srv.Close()

	tc := transport.NewClientWithDoer(srv.URL, "test-token", "Authorization", "Bearer ", srv.Client())
	client := dj.NewClient(tc, nil)
	var result dj.
	err := client.DoPost(context.Background(), "/test", map[string]any{}, &result)
	if err == nil {
		t.Fatal("expected error for 500 response")
	}

	apiErr, ok := err.(*transport.APIError)
	if !ok {
		t.Fatalf("expected *transport.APIError, got %T", err)
	}
	if apiErr.Code != contract.ErrCodeServer {
		t.Errorf("error code = %q, want %q", apiErr.Code, contract.ErrCodeServer)
	}
}

func TestCmdPause_ErrorMapping(t *testing.T) {
	tests := []struct {
		name       string
		statusCode int
		wantCode   string
	}{
		{"not_found", 404, contract.ErrCodeNotFound},
		{"unauthorized", 401, contract.ErrCodeUnauthorized},
		{"rate_limited", 429, contract.ErrCodeRateLimited},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.WriteHeader(tt.statusCode)
				w.Write([]byte(`{"error": "test error"}`))
			}))
			defer srv.Close()

			tc := transport.NewClientWithDoer(srv.URL, "test-token", "Authorization", "Bearer ", srv.Client())
			client := dj.NewClient(tc, nil)
			var result dj.
			err := client.DoPost(context.Background(), "/test", map[string]any{}, &result)
			if err == nil {
				t.Fatal("expected error")
			}

			apiErr, ok := err.(*transport.APIError)
			if !ok {
				t.Fatalf("expected *transport.APIError, got %T", err)
			}
			if apiErr.Code != tt.wantCode {
				t.Errorf("error code = %q, want %q", apiErr.Code, tt.wantCode)
			}
		})
	}
}

// Ensure unused imports are referenced.
var _ = json.Marshal
