// Code generated by marten vdev; DO NOT EDIT.

package player

import (
	"github.com/spf13/cobra"
	"strings"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/scale-flow/dj/internal/cli/cliutil"
	"github.com/scale-flow/dj/internal/dj"
)

func newPlayCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "play",
		Short: "Start or resume playback (Premium required)",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPlay(cmd, args)
		},
	}

	cmd.Flags().String("device-id", "", "Target device ID (defaults to active device)")
	cmd.Flags().String("context-uri", "", "Spotify URI of album, artist, or playlist to play")
	cmd.Flags().String("uris", "", "Comma-separated Spotify track URIs to play")
	cmd.Flags().Int("position-ms", 0, "Position in milliseconds to start playback")

	return cmd
}

func runPlay(cmd *cobra.Command, args []string) error {
	rctx, err := cliutil.ResolveSpotifyContext(cmd)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	client := dj.NewClient(nil, rctx.Extra)
	flagDeviceID, _ := cmd.Flags().GetString("device-id")
	flagContextURI, _ := cmd.Flags().GetString("context-uri")
	flagUris, _ := cmd.Flags().GetString("uris")
	flagPositionMs, _ := cmd.Flags().GetInt("position-ms")

	body := map[string]any{}
	if flagContextURI != "" {
		body["context_uri"] = flagContextURI
	}
	if flagUris != "" {
		body["uris"] = strings.Split(flagUris, ",")
	}
	if flagPositionMs != 0 {
		body["position_ms"] = flagPositionMs
	}
	pathParams := map[string]string{}
	fullPath := client.BuildPath("/v1/me/player/play", pathParams)
	queryParams := map[string]string{
		"device_id": flagDeviceID,
	}
	fullPath += dj.BuildQueryString(queryParams)

	if cmdutil.DryRun(cmd) {
		return cmdutil.WriteDryRun(cmd, "PUT", rctx.BaseURL+fullPath, body)
	}

	if !cliutil.ConfirmAction(cmd, "PUT /me/player/play") {
		return cmdutil.WriteSuccess(cmd, map[string]any{"status": "cancelled"})
	}
	client, err = cliutil.NewSpotifyClient(cmd, rctx)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	if err := client.DoMethod(cmd.Context(), "PUT", fullPath, body, nil); err != nil {
		return cliutil.WriteAPIError(cmd, err)
	}
	return cmdutil.WriteSuccess(cmd, nil)
}
