// Code generated by marten vdev; DO NOT EDIT.

package player

import "github.com/spf13/cobra"

// NewPlayerCmd creates the player parent command.
func NewPlayerCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "player",
		Short: "Playback control and status",
	}

	cmd.AddCommand(newNowPlayingCmd())
	cmd.AddCommand(newStatusCmd())
	cmd.AddCommand(newDevicesCmd())
	cmd.AddCommand(newPlayCmd())
	cmd.AddCommand(newPauseCmd())
	cmd.AddCommand(newNextCmd())
	cmd.AddCommand(newPreviousCmd())

	return cmd
}
