// Code generated by marten vdev; DO NOT EDIT.

package player

import (
	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/scale-flow/dj/internal/cli/cliutil"
	"github.com/scale-flow/dj/internal/dj"
)

func newPreviousCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "previous",
		Short: "Skip to previous track (Premium required)",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPrevious(cmd, args)
		},
	}

	cmd.Flags().String("device-id", "", "Target device ID (defaults to active device)")

	return cmd
}

func runPrevious(cmd *cobra.Command, args []string) error {
	rctx, err := cliutil.ResolveSpotifyContext(cmd)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	client := dj.NewClient(nil, rctx.Extra)
	flagDeviceID, _ := cmd.Flags().GetString("device-id")

	body := map[string]any{}
	pathParams := map[string]string{}
	fullPath := client.BuildPath("/v1/me/player/previous", pathParams)
	queryParams := map[string]string{
		"device_id": flagDeviceID,
	}
	fullPath += dj.BuildQueryString(queryParams)

	if cmdutil.DryRun(cmd) {
		return cmdutil.WriteDryRun(cmd, "POST", rctx.BaseURL+fullPath, body)
	}

	if !cliutil.ConfirmAction(cmd, "POST /me/player/previous") {
		return cmdutil.WriteSuccess(cmd, map[string]any{"status": "cancelled"})
	}
	client, err = cliutil.NewSpotifyClient(cmd, rctx)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	if err := client.DoMethod(cmd.Context(), "POST", fullPath, body, nil); err != nil {
		return cliutil.WriteAPIError(cmd, err)
	}
	return cmdutil.WriteSuccess(cmd, nil)
}
