// Code generated by marten vdev; DO NOT EDIT.

package player

import (
	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
	"github.com/Scale-Flow/marten/pkg/transport"
	"github.com/scale-flow/dj/internal/dj"
)

func newStatusCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Show full playback state including device, shuffle, and repeat",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runStatus(cmd, args)
		},
	}

	cmd.Flags().String("market", "", "ISO 3166-1 alpha-2 country code")

	return cmd
}

func runStatus(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	token, err := cmdutil.ResolveAuth(cmd.Context(), cmdutil.AuthConfig{
		Strategy:          "oauth2",
		ConfigDir:         "dj",
		ProfileName:       rctx.ProfileName,
		AllowFileFallback: true,
		OAuthStorePath:    storePath,
		OAuthMetadataPath: oauthMetadataPath(storePath),
		RefreshConfig: &oauth.RefreshConfig{
			TokenURL: "https://accounts.spotify.com/api/token",
		},
	})
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	t := transport.NewClient(rctx.BaseURL, token, "Authorization", "Bearer ")
	client := dj.NewClient(t, rctx.Extra)
	flagMarket, _ := cmd.Flags().GetString("market")

	if cmdutil.DryRun(cmd) {
		pathParams := map[string]string{}
		fullPath := client.BuildPath("/v1/me/player", pathParams)
		return cmdutil.WriteDryRun(cmd, "GET", rctx.BaseURL+fullPath, nil)
	}

	pathParams := map[string]string{}
	fullPath := client.BuildPath("/v1/me/player", pathParams)
	queryParams := map[string]string{
		"market": flagMarket,
	}
	fullPath += dj.BuildQueryString(queryParams)

	var result dj.PlaybackState
	if err := client.DoGet(cmd.Context(), fullPath, &result); err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeServer, err.Error())
	}
	return cmdutil.WriteSuccess(cmd, result)
}
