// Code generated by marten vdev; DO NOT EDIT.

package main

import (
	"os"

	"github.com/scale-flow/dj/internal/cli"
	"github.com/Scale-Flow/marten/pkg/cmdutil"
)

var version = "dev"

func main() {
	cmd := cli.NewRootCmd(version)
	if err := cmd.Execute(); err != nil {
		os.Exit(cmdutil.ExitCode(err))
	}
}
