// Code generated by marten vdev; DO NOT EDIT.

package main

import (
	"os"

	"github.com/scale-flow/dj/internal/cli"
)

var version = "dev"

func main() {
	cmd := cli.NewRootCmd(version)
	os.Exit(cli.Execute(cmd))
}
