// Code generated by marten vdev; DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// ManifestCommand describes a CLI command for machine consumption.
type ManifestCommand struct {
	Name        string            `json:"name"`
	FullName    string            `json:"full_name"`
	Description string            `json:"description"`
	Flags       []ManifestFlag    `json:"flags,omitempty"`
	Subcommands []ManifestCommand `json:"subcommands,omitempty"`
	Operation   string            `json:"operation,omitempty"` // read, create, update, delete, workflow, auth
}

// ManifestFlag describes a CLI flag for machine consumption.
type ManifestFlag struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Required    bool   `json:"required,omitempty"`
	Description string `json:"description,omitempty"`
	Persistent  bool   `json:"persistent,omitempty"`
}

// Manifest is the top-level manifest document.
type Manifest struct {
	Name        string            `json:"name"`
	Version     string            `json:"version"`
	Description string            `json:"description"`
	Commands    []ManifestCommand `json:"commands"`
	ErrorCodes  []ManifestError   `json:"error_codes"`
	ExitCodes   []ManifestExit    `json:"exit_codes"`
}

// ManifestError describes a known error code.
type ManifestError struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

// ManifestExit describes a semantic exit code.
type ManifestExit struct {
	Code        int    `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func newManifestCmd(version string) *cobra.Command {
	return &cobra.Command{
		Use:    "manifest",
		Short:  "Print machine-readable command manifest",
		Hidden: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			root := cmd.Root()
			m := Manifest{
				Name:        root.Use,
				Version:     version,
				Description: root.Short,
				Commands:    buildManifestCommands(root),
				ErrorCodes:  defaultErrorCodes(),
				ExitCodes:   defaultExitCodes(),
			}

			data, err := json.MarshalIndent(m, "", "  ")
			if err != nil {
				return fmt.Errorf("manifest: marshal: %w", err)
			}
			fmt.Fprintln(cmd.OutOrStdout(), string(data))
			return nil
		},
	}
}

func buildManifestCommands(cmd *cobra.Command) []ManifestCommand {
	var result []ManifestCommand
	for _, sub := range cmd.Commands() {
		if sub.Hidden || sub.Name() == "help" || sub.Name() == "completion" || sub.Name() == "manifest" {
			continue
		}
		mc := ManifestCommand{
			Name:        sub.Name(),
			FullName:    sub.CommandPath(),
			Description: sub.Short,
			Operation:   classifyOperation(sub),
		}

		// Local flags.
		sub.LocalFlags().VisitAll(func(f *pflag.Flag) {
			mc.Flags = append(mc.Flags, ManifestFlag{
				Name:        f.Name,
				Type:        f.Value.Type(),
				Description: f.Usage,
			})
		})

		// Recurse into subcommands.
		if sub.HasSubCommands() {
			mc.Subcommands = buildManifestCommands(sub)
		}

		result = append(result, mc)
	}
	return result
}

func classifyOperation(cmd *cobra.Command) string {
	name := cmd.Name()
	switch {
	case name == "auth" || name == "login" || name == "status" || name == "clear" || name == "set":
		return "auth"
	case name == "list" || name == "get" || name == "show" || name == "search":
		return "read"
	case name == "create" || name == "add" || name == "new":
		return "create"
	case name == "update" || name == "edit" || name == "modify":
		return "update"
	case name == "delete" || name == "remove" || name == "destroy":
		return "delete"
	default:
		if cmd.HasSubCommands() {
			return "" // parent command, no operation
		}
		return "action"
	}
}

func defaultErrorCodes() []ManifestError {
	return []ManifestError{
		{Code: "unauthorized", Description: "Authentication credentials are missing or invalid"},
		{Code: "forbidden", Description: "Authenticated but lacking required permissions"},
		{Code: "not_found", Description: "Requested resource does not exist"},
		{Code: "validation_error", Description: "Request parameters failed validation"},
		{Code: "rate_limited", Description: "Too many requests, retry after backoff"},
		{Code: "server_error", Description: "Unexpected error from the API server"},
		{Code: "network_error", Description: "Could not connect to the API server"},
		{Code: "config_error", Description: "Configuration is missing or invalid"},
		{Code: "auth_error", Description: "Authentication flow failed"},
	}
}

func defaultExitCodes() []ManifestExit {
	return []ManifestExit{
		{Code: 0, Name: "success", Description: "Command completed successfully"},
		{Code: 1, Name: "api_error", Description: "API returned an error"},
		{Code: 2, Name: "usage_error", Description: "Invalid command usage or validation failure"},
		{Code: 3, Name: "auth_error", Description: "Authentication required or failed"},
		{Code: 4, Name: "rate_limited", Description: "Rate limit exceeded"},
		{Code: 5, Name: "network_error", Description: "Network connectivity failure"},
		{Code: 6, Name: "config_error", Description: "Configuration problem"},
	}
}
