// Code generated by marten vdev; DO NOT EDIT.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/scale-flow/dj/internal/cli/auth"
	"github.com/scale-flow/dj/internal/cli/player"
	"github.com/scale-flow/dj/internal/cli/tracks"
	"github.com/scale-flow/dj/internal/cli/albums"
	"github.com/scale-flow/dj/internal/cli/search"
)

func NewRootCmd(version string) *cobra.Command {
	cmd := &cobra.Command{
		Use:           "dj",
		Short:         "Spotify player control and music lookup CLI",
		SilenceErrors: true,
		SilenceUsage:  true,
	}

	cmd.PersistentFlags().Bool("pretty", false, "Pretty-print JSON output")
	cmd.PersistentFlags().Bool("dry-run", false, "Show what would be done without making changes")
	cmd.PersistentFlags().Bool("yes", false, "Skip confirmation prompts")
	cmd.PersistentFlags().String("profile", "", "Configuration profile to use")
	cmd.PersistentFlags().String("base-url", "", "Override the API base URL")

	cmd.AddCommand(&cobra.Command{
		Use:   "version",
		Short: "Print version information",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println(version)
		},
	})

	cmd.AddCommand(newManifestCmd(version))
	cmd.AddCommand(auth.NewAuthCmd())
	cmd.AddCommand(player.NewPlayerCmd())
	cmd.AddCommand(tracks.NewTracksCmd())
	cmd.AddCommand(albums.NewAlbumsCmd())
	cmd.AddCommand(search.NewSearchCmd())

	return cmd
}
