// Code generated by marten vdev; DO NOT EDIT.

package albums

import "github.com/spf13/cobra"

// NewAlbumsCmd creates the albums parent command.
func NewAlbumsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "albums",
		Short: "Look up album information",
	}

	cmd.AddCommand(newGetCmd())
	cmd.AddCommand(newTracksCmd())

	return cmd
}
