// Code generated by marten vdev; DO NOT EDIT.

package albums

import (
	"fmt"
	"os"
	"path/filepath"
)

func oauthStorePath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("cannot determine home directory: %w", err)
	}
	return filepath.Join(home, ".config", "dj", "oauth-tokens.json"), nil
}
