// Code generated by marten vdev; DO NOT EDIT.

package albums

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"

	"github.com/scale-flow/dj/internal/dj"
	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
	"github.com/Scale-Flow/marten/pkg/transport"
)

func newTracksCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tracks",
		Short: "List tracks on an album",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runTracks(cmd, args)
		},
	}

	cmd.Flags().String("market", "", "ISO 3166-1 alpha-2 country code")
	cmd.Flags().String("id", "", "Spotify album ID")
	_ = cmd.MarkFlagRequired("id")
	cmdutil.AddPaginationFlags(cmd)

	return cmd
}

func runTracks(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	token, err := cmdutil.ResolveAuth(cmd.Context(), cmdutil.AuthConfig{
		Strategy:       "oauth2",
		ProfileName:    rctx.ProfileName,
		OAuthStorePath: storePath,
		RefreshConfig: &oauth.RefreshConfig{
			TokenURL:     "https://accounts.spotify.com/api/token",
			ClientID:     os.Getenv("DJ_CLIENT_ID"),
		},
	})
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	t := transport.NewClient(rctx.BaseURL, token, "Authorization", "Bearer ")
	client := dj.NewClient(t, rctx.Extra)
	flagMarket, _ := cmd.Flags().GetString("market")
	flagID, _ := cmd.Flags().GetString("id")

	pf := cmdutil.GetPaginationFlags(cmd)

	pathParams := map[string]string{
		"id": fmt.Sprintf("%v", flagID),
	}

	if cmdutil.DryRun(cmd) {
		fullPath := client.BuildPath("/v1/albums/{id}/tracks", pathParams)
		return cmdutil.WriteDryRun(cmd, "GET", rctx.BaseURL+fullPath, map[string]any{
			"paginated":        true,
			"pagination_style": "offset",
			"all":              pf.All,
			"page":             pf.Page,
			"per_page":         pf.PerPage,
		})
	}
	if pf.All {
		items, meta, err := cmdutil.ListAll[dj.TrackSimplified](cmd.Context(), func(ctx context.Context, page int) ([]dj.TrackSimplified, *contract.Pagination, error) {
			queryParams := map[string]string{
				"market": fmt.Sprintf("%v", flagMarket),
				"page":     fmt.Sprintf("%d", page),
				"per_page": fmt.Sprintf("%d", pf.PerPage),
			}
			fullPath := client.BuildPath("/v1/albums/{id}/tracks", pathParams) + dj.BuildQueryString(queryParams)
			resp, err := client.DoGetRaw(ctx, fullPath)
			if err != nil {
				return nil, nil, err
			}
			defer resp.Body.Close()
			body, _ := io.ReadAll(resp.Body)
			var raw map[string]json.RawMessage
			if err := json.Unmarshal(body, &raw); err != nil {
				return nil, nil, err
			}
			var items []dj.TrackSimplified
			if err := json.Unmarshal(raw["items"], &items); err != nil {
				return nil, nil, err
			}
			return items, &contract.Pagination{Page: page, PerPage: pf.PerPage}, nil
		}, pf.MaxPages)
		if err != nil {
			return cmdutil.WriteError(cmd, contract.ErrCodeServer, err.Error())
		}
		return cmdutil.WriteList(cmd, items, contract.Meta{Pagination: meta})
	}

	// Single page fetch.
	queryParams := map[string]string{
		"market": fmt.Sprintf("%v", flagMarket),
		"page":     fmt.Sprintf("%d", pf.Page),
		"per_page": fmt.Sprintf("%d", pf.PerPage),
	}
	fullPath := client.BuildPath("/v1/albums/{id}/tracks", pathParams) + dj.BuildQueryString(queryParams)
	resp, err := client.DoGetRaw(cmd.Context(), fullPath)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeServer, err.Error())
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(body, &raw); err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeServer, err.Error())
	}
	var result []dj.TrackSimplified
	if err := json.Unmarshal(raw["items"], &result); err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeServer, err.Error())
	}
	return cmdutil.WriteList(cmd, result, contract.Meta{Pagination: &contract.Pagination{Page: pf.Page, PerPage: pf.PerPage, TotalCount: len(result)}})
}
