// Code generated by marten vdev; DO NOT EDIT.

package dj

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/Scale-Flow/marten/pkg/transport"
)

// Client wraps the transport layer for API requests.
type Client struct {
	t     *transport.Client
	extra map[string]string
}

// NewClient creates a new API client.
func NewClient(t *transport.Client, extra map[string]string) *Client {
	return &Client{t: t, extra: extra}
}

// BuildPath replaces {param} placeholders in a path pattern with values
// from the params map, falling back to the extra map for unresolved params.
func (c *Client) BuildPath(pattern string, params map[string]string) string {
	result := pattern
	for k, v := range params {
		result = strings.ReplaceAll(result, "{"+k+"}", v)
	}
	for k, v := range c.extra {
		result = strings.ReplaceAll(result, "{"+k+"}", v)
	}
	return result
}

// BuildQueryString builds a URL query string from a map of parameters.
// Empty values are omitted.
func BuildQueryString(params map[string]string) string {
	vals := url.Values{}
	for k, v := range params {
		if v != "" {
			vals.Set(k, v)
		}
	}
	encoded := vals.Encode()
	if encoded == "" {
		return ""
	}
	return "?" + encoded
}

// DoGet performs a GET request and decodes the JSON response into target.
func (c *Client) DoGet(ctx context.Context, path string, target any) error {
	resp, err := c.t.DoWithRetry(ctx, "GET", path, nil)
	if err != nil {
		return fmt.Errorf("get %s: %w", path, err)
	}
	return c.t.DecodeResponse(resp, target)
}

// DoPost marshals body as JSON, performs a POST request, and decodes the response into target.
func (c *Client) DoPost(ctx context.Context, path string, body any, target any) error {
	data, err := json.Marshal(body)
	if err != nil {
		return fmt.Errorf("marshal body: %w", err)
	}
	resp, err := c.t.Do(ctx, "POST", path, data)
	if err != nil {
		return fmt.Errorf("post %s: %w", path, err)
	}
	return c.t.DecodeResponse(resp, target)
}

// DoGetRaw performs a GET request and returns the raw HTTP response.
// The caller is responsible for closing the response body.
func (c *Client) DoGetRaw(ctx context.Context, path string) (*http.Response, error) {
	return c.t.DoWithRetry(ctx, "GET", path, nil)
}

// DoMethod performs an HTTP request with the given method and JSON body.
func (c *Client) DoMethod(ctx context.Context, method, path string, body any, target any) error {
	var reqBody []byte
	if body != nil {
		var err error
		reqBody, err = json.Marshal(body)
		if err != nil {
			return fmt.Errorf("marshal body: %w", err)
		}
	}
	resp, err := c.t.Do(ctx, method, path, reqBody)
	if err != nil {
		return fmt.Errorf("%s %s: %w", strings.ToLower(method), path, err)
	}
	return c.t.DecodeResponse(resp, target)
}

// DoPostForm performs a POST request with form-encoded body.
func (c *Client) DoPostForm(ctx context.Context, path string, fields map[string]string, target any) error {
	resp, err := c.t.DoForm(ctx, "POST", path, fields)
	if err != nil {
		return fmt.Errorf("post form %s: %w", path, err)
	}
	return c.t.DecodeResponse(resp, target)
}
