// Code generated by marten vdev; DO NOT EDIT.

package auth

import "github.com/spf13/cobra"

// NewAuthCmd creates the auth parent command.
func NewAuthCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auth",
		Short: "Manage authentication credentials",
	}
	cmd.AddCommand(newAuthLoginCmd())
	cmd.AddCommand(newAuthStatusCmd())
	cmd.AddCommand(newAuthClearCmd())

	return cmd
}
