// Code generated by marten vdev; DO NOT EDIT.

package auth

import (
	"errors"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
)

func newAuthClearCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "clear",
		Short: "Remove stored credentials",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthClear(cmd, args)
		},
	}

	return cmd
}

func runAuthClear(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	var clearErrs []error
	keychainStore := oauth.NewKeychainStore("dj")
	if err := keychainStore.Delete(rctx.ProfileName); err != nil {
		if !shouldIgnoreOAuthKeychainError(err) {
			clearErrs = append(clearErrs, err)
		}
	}
	fileStore := oauth.NewOAuthStore(storePath)
	if err := fileStore.Delete(rctx.ProfileName); err != nil {
		clearErrs = append(clearErrs, err)
	}
	metaStore := oauth.NewMetadataStore(oauth.MetadataPathForTokenStore(storePath))
	if err := metaStore.Delete(rctx.ProfileName); err != nil {
		clearErrs = append(clearErrs, err)
	}
	clientCredPath := oauth.ClientCredentialPathForTokenStore(storePath)
	clientCredKeychainStore := oauth.NewClientCredentialKeychainStore("dj")
	if err := clientCredKeychainStore.Delete(rctx.ProfileName); err != nil {
		if !shouldIgnoreOAuthKeychainError(err) {
			clearErrs = append(clearErrs, err)
		}
	}
	clientCredFileStore := oauth.NewClientCredentialFileStore(clientCredPath)
	if err := clientCredFileStore.Delete(rctx.ProfileName); err != nil {
		clearErrs = append(clearErrs, err)
	}
	if len(clearErrs) > 0 {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, errors.Join(clearErrs...).Error())
	}

	return cmdutil.WriteSuccess(cmd, map[string]any{
		"profile": rctx.ProfileName,
		"status":  "cleared",
	})
}

func shouldIgnoreOAuthKeychainError(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "unsupported platform") ||
		strings.Contains(msg, "keychain backend unavailable") ||
		strings.Contains(msg, "credential backend unavailable") ||
		strings.Contains(msg, "no credential backend available") ||
		strings.Contains(msg, "the name org.freedesktop.secrets was not provided by any .service files")
}
