// Code generated by marten vdev; DO NOT EDIT.

package auth

import (
	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
)

func newAuthClearCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "clear",
		Short: "Remove stored credentials",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthClear(cmd, args)
		},
	}

	return cmd
}

func runAuthClear(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	store := oauth.NewOAuthStore(storePath)
	if err := store.Delete(rctx.ProfileName); err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	return cmdutil.WriteSuccess(cmd, map[string]any{
		"profile": rctx.ProfileName,
		"status":  "cleared",
	})
}
