// Code generated by marten vdev; DO NOT EDIT.

package auth

import (
	"errors"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
	"github.com/scale-flow/dj/internal/cli/cliutil"
)

func newAuthClearCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "clear",
		Short: "Remove stored credentials",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthClear(cmd, args)
		},
	}

	return cmd
}

func runAuthClear(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	backend := cliutil.OAuthStorage(cmd)
	if cmdutil.DryRun(cmd) {
		return cmdutil.WriteSuccess(cmd, map[string]any{
			"dry_run": true, "action": "auth clear", "profile": rctx.ProfileName, "storage": backend,
			"resources": authClearResources(backend),
		})
	}
	if !cliutil.ConfirmAction(cmd, fmt.Sprintf("remove stored credentials for profile %q", rctx.ProfileName)) {
		return cmdutil.WriteSuccess(cmd, map[string]any{"profile": rctx.ProfileName, "status": "cancelled"})
	}

	var clearErrs []error
	for _, store := range authClearStores(storePath, backend) {
		if err := store.delete(rctx.ProfileName); err != nil {
			if backend != "auto" || !store.keychain || !shouldIgnoreOAuthKeychainError(err) {
				clearErrs = append(clearErrs, err)
			}
		}
	}
	if len(clearErrs) > 0 {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, errors.Join(clearErrs...).Error())
	}

	return cmdutil.WriteSuccess(cmd, map[string]any{
		"profile": rctx.ProfileName,
		"status":  "cleared",
	})
}

func authClearResources(backend string) []string {
	resources := []string{"oauth metadata"}
	if backend != "file" {
		resources = append(resources, "keychain OAuth tokens", "keychain client credentials")
	}
	if backend != "keychain" {
		resources = append(resources, "file OAuth tokens", "file client credentials")
	}
	return resources
}

// Keep store construction behind the safety checks: dry-run and a declined
// confirmation must not even contact a credential backend.
type authClearStore struct {
	delete   func(string) error
	keychain bool
}

var authClearStores = func(storePath, backend string) []authClearStore {
	var stores []authClearStore
	if backend != "file" {
		stores = append(stores,
			authClearStore{oauth.NewKeychainStore("dj").Delete, true},
			authClearStore{oauth.NewClientCredentialKeychainStore("dj").Delete, true},
		)
	}
	if backend != "keychain" {
		stores = append(stores,
			authClearStore{oauth.NewOAuthStore(storePath).Delete, false},
			authClearStore{oauth.NewClientCredentialFileStore(oauth.ClientCredentialPathForTokenStore(storePath)).Delete, false},
		)
	}
	return append(stores, authClearStore{oauth.NewMetadataStore(oauth.MetadataPathForTokenStore(storePath)).Delete, false})
}

func shouldIgnoreOAuthKeychainError(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "unsupported platform") ||
		strings.Contains(msg, "keychain backend unavailable") ||
		strings.Contains(msg, "credential backend unavailable") ||
		strings.Contains(msg, "no credential backend available") ||
		strings.Contains(msg, "the name org.freedesktop.secrets was not provided by any .service files")
}
