// Code generated by marten vdev; DO NOT EDIT.

package auth

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/signal"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
	"github.com/scale-flow/dj/internal/cli/cliutil"
)

func newAuthLoginCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "login",
		Short: "Authenticate via OAuth2",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthLogin(cmd, args)
		},
	}
	cmd.Flags().Bool("local", false, "Use loopback callback server instead of the HTTPS relay")
	cmd.Flags().Duration("timeout", 2*time.Minute, "Maximum login duration (positive, at most 10m)")
	cmd.Args = cobra.NoArgs
	addHeadlessCommands(cmd)
	return cmd
}

func runAuthLogin(cmd *cobra.Command, args []string) error {
	timeout, _ := cmd.Flags().GetDuration("timeout")
	if timeout <= 0 || timeout > 10*time.Minute {
		return cmdutil.WriteError(cmd, contract.ErrCodeValidation, "timeout must be positive and at most 10m")
	}
	dry, _ := cmd.Flags().GetBool("dry-run")
	if dry {
		return cmdutil.WriteSuccess(cmd, map[string]any{"dry_run": true, "action": "auth login"})
	}
	signalCtx, stop := signal.NotifyContext(cmd.Context(), os.Interrupt)
	defer stop()
	ctx, cancel := context.WithTimeout(signalCtx, timeout)
	defer cancel()
	cmd.SetContext(ctx)
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	creds, err := resolveClientCredentials(cmd, rctx.ProfileName)
	if err != nil {
		if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
			return cmdutil.WriteError(cmd, contract.ErrCodeAuth, "login timed out or was cancelled; start a new login")
		}
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	useLocal, _ := cmd.Flags().GetBool("local")
	if useLocal {
		return runLocalCallbackFlow(cmd, rctx.ProfileName, creds)
	}

	return runManualCodeFlow(cmd, rctx.ProfileName, creds)
}

func resolveClientCredentials(cmd *cobra.Command, profile string) (oauth.ClientCredentials, error) {
	if err := cmd.Context().Err(); err != nil {
		return oauth.ClientCredentials{}, err
	}
	// 1. Env vars always win
	envID := os.Getenv("DJ_CLIENT_ID")
	envSecret := os.Getenv("DJ_CLIENT_SECRET")
	if envID != "" {
		return oauth.ClientCredentials{ClientID: envID, ClientSecret: envSecret}, nil
	}

	// 2. Check stored credentials
	storePath, err := oauthStorePath()
	if err == nil {
		creds, err := cliutil.LoadClientCredentials(cmd.Context(), "dj", storePath, profile, cliutil.OAuthStorage(cmd))
		if err != nil {
			return oauth.ClientCredentials{}, err
		}
		if creds != nil {
			in, ok := cmd.InOrStdin().(*os.File)
			if ok && cmdutil.IsInteractiveInput(in) {
				update, promptErr := confirmCredentialUpdate(cmd.Context(), in, cmd.ErrOrStderr())
				if promptErr != nil {
					return oauth.ClientCredentials{}, promptErr
				}
				if !update {
					return *creds, nil
				}
			} else {
				return *creds, nil
			}
		}
	}

	// 3. Interactive prompt
	clientID, err := resolveEnvOrPrompt(cmd, "DJ_CLIENT_ID", "Client ID", false, true)
	if err != nil {
		return oauth.ClientCredentials{}, err
	}
	clientSecret := ""
	clientSecret, err = resolveEnvOrPrompt(cmd, "DJ_CLIENT_SECRET", "Client Secret", true, false)
	if err != nil {
		return oauth.ClientCredentials{}, err
	}
	return oauth.ClientCredentials{ClientID: clientID, ClientSecret: clientSecret}, nil
}

var pollForAuthCode = oauth.PollForCode

func runManualCodeFlow(cmd *cobra.Command, profile string, creds oauth.ClientCredentials) error {
	ctx, stop := signal.NotifyContext(cmd.Context(), os.Interrupt)
	defer stop()

	redirectURI := "https://martencli.netlify.app/callback"

	cfg := oauth.AuthCodeConfig{
		AuthURL:      "https://accounts.spotify.com/authorize",
		TokenURL:     "https://accounts.spotify.com/api/token",
		ClientID:     creds.ClientID,
		ClientSecret: creds.ClientSecret,
		RedirectURI:  redirectURI,
		Scopes:       []string{"user-read-currently-playing", "user-read-playback-state", "user-modify-playback-state"},
		Quirks: oauth.Quirks{
			ForceConsent: false,
		},
	}

	result, err := oauth.BuildAuthURLWithState(cfg)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	fmt.Fprintf(cmd.ErrOrStderr(), "Open this URL in your browser:\n\n  %s\n\n", result.URL)

	// Race: poll the passthrough service vs manual paste.
	// Whichever delivers the code first wins.
	codeCh := make(chan string, 2)
	errCh := make(chan error, 1)
	// Start polling the passthrough service in the background
	pollCtx, pollCancel := context.WithCancel(ctx)
	defer pollCancel()
	go func() {
		code, err := pollForAuthCode(pollCtx, "https://martencli.netlify.app/api/poll", result.State, 2*time.Second, 120*time.Second)
		if err == nil {
			codeCh <- code
		} else {
			errCh <- err
		}
	}()

	// The paste reader must finish and restore terminal state before any result
	// is printed, including when the relay wins the race.
	promptCtx, promptCancel := context.WithCancel(ctx)
	promptDone := make(chan struct{})
	promptErrCh := make(chan error, 1)
	in, ok := cmd.InOrStdin().(*os.File)
	isInteractive := ok && cmdutil.IsInteractiveInput(in)
	if isInteractive {
		go func() {
			defer close(promptDone)
			code, err := readTerminalPrompt(promptCtx, in, cmd.ErrOrStderr(), "Paste the authorization code: ", true)
			if err == nil && code != "" {
				codeCh <- code
			} else if err != nil {
				promptErrCh <- err
			}
		}()
	} else {
		close(promptDone)
	}

	var code, failure string
	select {
	case code = <-codeCh:
	case <-errCh:
		failure = "login relay failed or timed out; retry, or use auth login start for headless PKCE"
	case <-promptErrCh:
		failure = "login input failed or was cancelled; start a new login"
	case <-ctx.Done():
		failure = "login timed out or was cancelled; start a new login"
	}
	promptCancel()
	<-promptDone
	pollCancel()
	if failure != "" {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, failure)
	}

	ts, err := oauth.ExchangeCode(ctx, cfg, code, result.Verifier)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	source, err := persistOAuthLoginForCommand(cmd, profile, creds, ts)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	return cmdutil.WriteSuccess(cmd, map[string]any{
		"profile": profile,
		"source":  source,
		"status":  "authenticated",
		"scopes":  ts.Scopes,
	})
}

func runLocalCallbackFlow(cmd *cobra.Command, profile string, creds oauth.ClientCredentials) error {
	ctx, stop := signal.NotifyContext(cmd.Context(), os.Interrupt)
	defer stop()

	redirectPort := 8085
	redirectURI := fmt.Sprintf("http://127.0.0.1:%d/callback", redirectPort)

	cfg := oauth.AuthCodeConfig{
		AuthURL:      "https://accounts.spotify.com/authorize",
		TokenURL:     "https://accounts.spotify.com/api/token",
		ClientID:     creds.ClientID,
		ClientSecret: creds.ClientSecret,
		RedirectURI:  redirectURI,
		Scopes:       []string{"user-read-currently-playing", "user-read-playback-state", "user-modify-playback-state"},
		Quirks: oauth.Quirks{
			ForceConsent: false,
		},
	}

	authResult, err := oauth.BuildAuthURLWithState(cfg)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	cb, err := startValidatedCallbackServer(redirectPort, authResult.State)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, fmt.Sprintf("start callback server: %s", err))
	}
	defer cb.Close()

	fmt.Fprintf(cmd.ErrOrStderr(), "Open this URL in your browser:\n\n  %s\n\nWaiting for authorization (Ctrl+C to cancel)...\n", authResult.URL)

	var code string
	select {
	case code = <-cb.CodeCh:
	case err := <-cb.ErrCh:
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	case <-ctx.Done():
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, "login timed out or was cancelled; start a new login")
	}

	ts, err := oauth.ExchangeCode(ctx, cfg, code, authResult.Verifier)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	source, err := persistOAuthLoginForCommand(cmd, profile, creds, ts)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	return cmdutil.WriteSuccess(cmd, map[string]any{
		"profile": profile,
		"source":  source,
		"status":  "authenticated",
		"scopes":  ts.Scopes,
	})
}

func persistOAuthLogin(profile string, creds oauth.ClientCredentials, ts *oauth.TokenSet) (string, error) {
	return persistOAuthLoginWithBackend(profile, creds, ts, "auto")
}

func persistOAuthLoginForCommand(cmd *cobra.Command, profile string, creds oauth.ClientCredentials, ts *oauth.TokenSet) (string, error) {
	return persistOAuthLoginContext(cmd.Context(), profile, creds, ts, cliutil.OAuthStorage(cmd))
}

func persistOAuthLoginWithBackend(profile string, creds oauth.ClientCredentials, ts *oauth.TokenSet, selectedBackend string) (string, error) {
	return persistOAuthLoginContext(context.Background(), profile, creds, ts, selectedBackend)
}

func persistOAuthLoginContext(ctx context.Context, profile string, creds oauth.ClientCredentials, ts *oauth.TokenSet, selectedBackend string) (string, error) {
	storePath, err := oauthStorePath()
	if err != nil {
		return "", err
	}
	return cliutil.PersistOAuthLogin(ctx, cmdutil.AuthConfig{
		ConfigDir: "dj", ProfileName: profile, OAuthStorePath: storePath,
		StorageBackend: selectedBackend, AllowFileFallback: true,
	}, creds, ts)
}

func oauthStorePath() (string, error) {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "dj", "oauth-tokens.json"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("cannot determine home directory: %w", err)
	}
	return filepath.Join(home, ".config", "dj", "oauth-tokens.json"), nil
}

func oauthMetadataPath(tokenPath string) string {
	return oauth.MetadataPathForTokenStore(tokenPath)
}
