// Code generated by marten vdev; DO NOT EDIT.

package auth

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
)

func newAuthLoginCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "login",
		Short: "Authenticate via OAuth2",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthLogin(cmd, args)
		},
	}
	return cmd
}

func runAuthLogin(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	clientID := os.Getenv("DJ_CLIENT_ID")
	if clientID == "" {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, "DJ_CLIENT_ID environment variable not set")
	}

	clientSecret := ""
	clientSecret = os.Getenv("DJ_CLIENT_SECRET")

	return runBrowserFlow(cmd, rctx.ProfileName, clientID, clientSecret)
}

func runBrowserFlow(cmd *cobra.Command, profile, clientID, clientSecret string) error {
	redirectPort := 8085
	redirectURI := fmt.Sprintf("http://localhost:%d/callback", redirectPort)

	cfg := oauth.AuthCodeConfig{
		AuthURL:      "https://accounts.spotify.com/authorize",
		TokenURL:     "https://accounts.spotify.com/api/token",
		ClientID:     clientID,
		ClientSecret: clientSecret,
		RedirectURI:  redirectURI,
		Scopes:       []string{"user-read-currently-playing", "user-read-playback-state", "user-modify-playback-state" },
		Quirks:       oauth.Quirks{
			ForceConsent: false,
		},
	}

	authURL, verifier, err := oauth.BuildAuthURL(cfg)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	cb, err := oauth.StartCallbackServer(redirectPort)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, fmt.Sprintf("start callback server: %s", err))
	}
	defer cb.Close()

	fmt.Fprintf(cmd.ErrOrStderr(), "Open this URL in your browser:\n\n  %s\n\nWaiting for authorization...\n", authURL)

	var code string
	select {
	case code = <-cb.CodeCh:
	case err := <-cb.ErrCh:
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	ts, err := oauth.ExchangeCode(cmd.Context(), cfg, code, verifier)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeAuth, err.Error())
	}

	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	store := oauth.NewOAuthStore(storePath)
	if err := store.Save(profile, *ts); err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}

	return cmdutil.WriteSuccess(cmd, map[string]any{
		"profile": profile,
		"status":  "authenticated",
		"scopes":  ts.Scopes,
	})
}

func oauthStorePath() (string, error) {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "dj", "oauth-tokens.json"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("cannot determine home directory: %w", err)
	}
	return filepath.Join(home, ".config", "dj", "oauth-tokens.json"), nil
}
