// Code generated by marten vdev; DO NOT EDIT.

package auth

import (
	"time"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
)

func newAuthStatusCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Show authentication status",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthStatus(cmd, args)
		},
	}

	return cmd
}

func runAuthStatus(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	store := oauth.NewOAuthStore(storePath)
	ts, err := store.Load(rctx.ProfileName)
	if err != nil {
		return cmdutil.WriteSuccess(cmd, map[string]any{
			"authenticated": false,
			"profile":       rctx.ProfileName,
		})
	}

	result := map[string]any{
		"authenticated": true,
		"profile":       rctx.ProfileName,
		"token":         maskToken(ts.AccessToken),
		"scopes":        ts.Scopes,
		"expired":       ts.IsExpired(),
	}
	if !ts.ExpiresAt.IsZero() {
		result["expires_at"] = ts.ExpiresAt.Format(time.RFC3339)
		result["expires_in_seconds"] = int(time.Until(ts.ExpiresAt).Seconds())
	}
	if ts.RefreshToken != "" {
		result["has_refresh_token"] = true
	}
	return cmdutil.WriteSuccess(cmd, result)
}

func maskToken(token string) string {
	if len(token) <= 8 {
		return "****"
	}
	return token[:4] + "..." + token[len(token)-4:]
}
