// Code generated by marten vdev; DO NOT EDIT.

package auth

import (
	"errors"
	"time"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
	"github.com/scale-flow/dj/internal/cli/cliutil"
)

func newAuthStatusCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Show authentication status",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthStatus(cmd, args)
		},
	}

	return cmd
}

func runAuthStatus(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	ts, creds, source, err := cliutil.LoadOAuthStatus(cmd.Context(), cmdutil.AuthConfig{
		ConfigDir: "dj", ProfileName: rctx.ProfileName,
		OAuthStorePath: storePath, StorageBackend: cliutil.OAuthStorage(cmd),
		AllowFileFallback: true,
	})
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	if ts == nil {
		return cmdutil.WriteSuccess(cmd, map[string]any{
			"authenticated":             false,
			"profile":                   rctx.ProfileName,
			"source":                    "",
			"token":                     "",
			"scopes":                    []string{},
			"expired":                   false,
			"expires_at":                "",
			"expires_in_seconds":        0,
			"has_refresh_token":         false,
			"client_credentials_stored": false,
			"client_credentials_source": "",
		})
	}

	meta, err := oauth.NewMetadataStore(oauth.MetadataPathForTokenStore(storePath)).Load(rctx.ProfileName)
	if err != nil && !errors.Is(err, oauth.ErrMetadataNotFound) {
		meta = nil
	}

	scopes := ts.Scopes
	expiresAt := ts.ExpiresAt
	if meta != nil && creds != nil && meta.ClientID == creds.ClientID {
		if len(scopes) == 0 && len(meta.Scopes) > 0 {
			scopes = meta.Scopes
		}
		if expiresAt.IsZero() && !meta.ExpiresAt.IsZero() {
			expiresAt = meta.ExpiresAt
		}
	}

	clientCredStored := creds != nil
	clientCredSource := ""
	if clientCredStored {
		clientCredSource = string(source)
	}

	result := map[string]any{
		"authenticated":      true,
		"profile":            rctx.ProfileName,
		"source":             string(source),
		"token":              maskToken(ts.AccessToken),
		"scopes":             scopes,
		"expired":            !expiresAt.IsZero() && time.Now().After(expiresAt),
		"expires_at":         "",
		"expires_in_seconds": 0,
	}
	if !expiresAt.IsZero() {
		result["expires_at"] = expiresAt.Format(time.RFC3339)
		result["expires_in_seconds"] = int(time.Until(expiresAt).Seconds())
	}
	result["has_refresh_token"] = ts.RefreshToken != ""
	result["client_credentials_stored"] = clientCredStored
	result["client_credentials_source"] = clientCredSource
	return cmdutil.WriteSuccess(cmd, result)
}

func maskToken(token string) string {
	if len(token) <= 8 {
		return "****"
	}
	return token[:4] + "..." + token[len(token)-4:]
}
