// Code generated by marten vdev; DO NOT EDIT.

package auth

import (
	"errors"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/Scale-Flow/marten/pkg/cmdutil"
	"github.com/Scale-Flow/marten/pkg/contract"
	"github.com/Scale-Flow/marten/pkg/oauth"
)

func newAuthStatusCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Show authentication status",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthStatus(cmd, args)
		},
	}

	return cmd
}

func runAuthStatus(cmd *cobra.Command, args []string) error {
	rctx, err := cmdutil.ResolveContext(cmd, "dj", "DJ")
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	storePath, err := oauthStorePath()
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	keychainStore := oauth.NewKeychainStore("dj")
	fileStore := oauth.NewOAuthStore(storePath)
	ts, source, err := loadOAuthStatusToken(rctx.ProfileName, keychainStore, fileStore)
	if err != nil {
		return cmdutil.WriteError(cmd, contract.ErrCodeConfig, err.Error())
	}
	if ts == nil {
		return cmdutil.WriteSuccess(cmd, map[string]any{
			"authenticated": false,
			"profile":       rctx.ProfileName,
			"source":        "",
			"token":         "",
			"scopes":        []string{},
			"expired":       false,
			"expires_at":    "",
			"expires_in_seconds": 0,
			"has_refresh_token": false,
			"client_credentials_stored": false,
			"client_credentials_source": "",
		})
	}

	meta, err := oauth.NewMetadataStore(oauth.MetadataPathForTokenStore(storePath)).Load(rctx.ProfileName)
	if err != nil && !errors.Is(err, oauth.ErrMetadataNotFound) {
		meta = nil
	}

	scopes := ts.Scopes
	expiresAt := ts.ExpiresAt
	if meta != nil {
		if len(scopes) == 0 && len(meta.Scopes) > 0 {
			scopes = meta.Scopes
		}
		if expiresAt.IsZero() && !meta.ExpiresAt.IsZero() {
			expiresAt = meta.ExpiresAt
		}
	}

	clientCredStored := false
	clientCredSource := ""
	if storePath != "" {
		clientCredPath := oauth.ClientCredentialPathForTokenStore(storePath)
		keychainCredStore := oauth.NewClientCredentialKeychainStore("dj")
		if _, err := keychainCredStore.Load(rctx.ProfileName); err == nil {
			clientCredStored = true
			clientCredSource = "keychain"
		} else {
			fileCredStore := oauth.NewClientCredentialFileStore(clientCredPath)
			if _, err := fileCredStore.Load(rctx.ProfileName); err == nil {
				clientCredStored = true
				clientCredSource = "file"
			}
		}
	}

	result := map[string]any{
		"authenticated": true,
		"profile":       rctx.ProfileName,
		"source":        string(source),
		"token":         maskToken(ts.AccessToken),
		"scopes":        scopes,
		"expired":       !expiresAt.IsZero() && time.Now().After(expiresAt),
		"expires_at":    "",
		"expires_in_seconds": 0,
	}
	if !expiresAt.IsZero() {
		result["expires_at"] = expiresAt.Format(time.RFC3339)
		result["expires_in_seconds"] = int(time.Until(expiresAt).Seconds())
	}
	result["has_refresh_token"] = ts.RefreshToken != ""
	result["client_credentials_stored"] = clientCredStored
	result["client_credentials_source"] = clientCredSource
	return cmdutil.WriteSuccess(cmd, result)
}

func maskToken(token string) string {
	if len(token) <= 8 {
		return "****"
	}
	return token[:4] + "..." + token[len(token)-4:]
}

func loadOAuthStatusToken(profile string, keychainStore, fileStore oauth.Store) (*oauth.TokenSet, cmdutil.CredentialBackend, error) {
	ts, err := keychainStore.Load(profile)
	if err == nil {
		return ts, cmdutil.CredentialBackendKeychain, nil
	}
	keychainErr := err
	if errors.Is(err, oauth.ErrTokenNotFound) {
		ts, availableInPrimary, err := oauth.LoadMigrating(profile, keychainStore, fileStore)
		if err == nil {
			if availableInPrimary {
				return ts, cmdutil.CredentialBackendKeychain, nil
			}
			return ts, cmdutil.CredentialBackendFile, nil
		}
		if !errors.Is(err, oauth.ErrTokenNotFound) {
			return nil, "", err
		}
	}

	ts, err = fileStore.Load(profile)
	if err == nil {
		return ts, cmdutil.CredentialBackendFile, nil
	}
	if !errors.Is(err, oauth.ErrTokenNotFound) {
		return nil, "", err
	}
	if keychainErr != nil && !errors.Is(keychainErr, oauth.ErrTokenNotFound) && !shouldIgnoreOAuthStatusKeychainError(keychainErr) {
		return nil, "", keychainErr
	}
	return nil, "", nil
}

func shouldIgnoreOAuthStatusKeychainError(err error) bool {
	if err == nil {
		return false
	}
	msg := strings.ToLower(err.Error())
	return strings.Contains(msg, "unsupported platform") ||
		strings.Contains(msg, "keychain backend unavailable") ||
		strings.Contains(msg, "credential backend unavailable") ||
		strings.Contains(msg, "no credential backend available") ||
		strings.Contains(msg, "the name org.freedesktop.secrets was not provided by any .service files")
}
